### ISSUE TITLE
Ability to change the frequency in which sensor data is pulled.

### ISSUE THREAD

**Issue by almighty059** [dalinicus/homeassistant-acinfinity#32]
The integration seems to pull data every 30 seconds or at least that's what it shows in the history on Home Assistant. I have automations setup in Home Assistant that trigger when there are changes in temperature, humidity, and vpd. Since there are three event that I use as triggers my automation is being run more than I would like it to. Is there anyway to add a feature to change the frequency in which the data is being pulled? So instead of it being 30 seconds I could change it to 1 min or 2 minutes? 

As I was writing this I thought of a possible work around for now which I think would work. I all three of the above mentioned sensors pull data at 30 second intervals then I could probably just use one of them as a trigger. I could then probably setup condition in my automation that check the state of all three sensors and then preform any actions accordingly. That should work to decrease the amount of times the automation is run from 6 times a minute to 2 times a minute but that's it. A feature that adds the option to change the frequency in which the data is being pulled would allow me to decrease that even more.

**Comment by dalinicus** [comment]
Are you using the 1.1 release or the main branch?  I refactored the data polling to use the home assistant built it data coordinators instead of ad-hoc poling... the changes also add like 15 new setting entities per device connected to the controller, so I was working on a custom lovelace card to organize them all before I released it at version 1.2.

I'll take a look around the HA API for the data coordinator and see if there's an update interval setting.  If so, I'll throw an option in the config dialog for it :)

**Comment by dalinicus** [comment]
![image](https://github.com/dalinicus/homeassistant-acinfinity/assets/8620219/c2782235-9699-444d-ba5e-d8c9644ae154)
Sure is  :)  I'll whip you up a change.

**Comment by dalinicus** [comment]
This will be included in the 1.2.0 release.  I've published a pre-release version that include this and many other changes since the last release.  If you'd like to use this feature now, you can enable beta versions from the "Re-download" dialog in HACS

![image](https://github.com/dalinicus/homeassistant-acinfinity/assets/8620219/04b3c33d-be10-4ac2-9160-e713388847c0)
![image](https://github.com/dalinicus/homeassistant-acinfinity/assets/8620219/1a96c2b5-d091-47a3-95e4-8c5c2da6be68)

**Comment by dalinicus** [comment]
![additional-configuration](https://github.com/dalinicus/homeassistant-acinfinity/assets/8620219/186577b9-a6dc-4afc-a747-0071f9942ddc)
