### ISSUE TITLE
vpd not pulling from correct hex value

### ISSUE THREAD

**Issue by mikeybatoz** [dalinicus/homeassistant-acinfinity#45]
puled bluetooth input and your not readin the correct hex value for vpd being sent by the system. please address.

**Comment by dalinicus** [comment]
This repository is for the UIS cloud integration for 69 series controllers, and is not associated with the bluetooth integration efforts for 67 series controllers.  This repository does not offer direct bluetooth support.

You can find that discussion here:  https://community.home-assistant.io/t/ac-infinity-controller-67-bluetooth-temp-humidity-fan-pwm/410673/21

Closing.

**Comment by almighty059** [comment]
> puled bluetooth input and your not readin the correct hex value for vpd being sent by the system. please address.

@mikeybatoz this might also be because HA defaults and shows the value in the incorrect measurement of PSI. I'm not sure if this is something that @dalinicus can change in the integration but I changed it myself. Go to the VPD sensor and change the Unit of Measurement from PSI to kPa and you'll be set. I'm not sure if this is what you meant but it seemed like it from your description.

![image](https://github.com/dalinicus/homeassistant-acinfinity/assets/63380298/a1147001-e204-4c6f-8f1c-273de002d8a3)
