### ISSUE TITLE
Controller69 without WLAN - just BT

### ISSUE THREAD

**Issue by kontaktgift** [dalinicus/homeassistant-acinfinity#55]
Can't connect with controller 69 could not be found or connected

I installed this integration with HACS - without any errors.

I entered my cloud mail, and password - it seems to work
I changed the configuration from 10 to 5 seconds - it seems to work

Now there is no device and no entities, it seems that there is no connection to the controller.
How could I fix this?

Is there any advice?

AC INFINITY UPDATE SAYS 1.4.3

**Comment by dalinicus** [comment]
Based on your title, it sounds like youre using bluetooth instead of wifi?

This integration only works with wifi, as it interacts with the AC Infintiy cloud api to get its data.  If you're using bluetooth, your controller would only interact with your phone and not the api... so the integration would have no idea your controller exists.

If you are using wifi.. can you confirm that your controller is added and exists in the AC infinity app.  Then please provide your homeassistant logs to see if there are any errors during integration setup that would prevent the integration from working properly.

**Comment by kontaktgift** [comment]
Hallo,
Thx for your answer.
I‘m a little bit confused, while the Controller 69 only has BT and you descriped for all Controller exapt 67.

Okay - than I have to look for another solution.

**Comment by dalinicus** [comment]
From the product specs ive observed, all 69 models are wifi capable, and I do specify that this is not compatable with bluetooth only devices. I'm on vacation, but ill take a second look at the product models when I return.

I could be more susinct that this integration is only compatible with the wifi functionality and not bluetooth.  Ill update the readme to reflect that.  

Thanks for the report.

**Comment by dalinicus** [comment]
Was working on another feature request, and it crossed my mind that I never checked up on this.  You're correct; looks like theres a wifi and non-wifi version of the base model of Controller 69.  I'll update the readme to reflect.  Sorry for the confusion.
