### ISSUE TITLE
Change/Add duration for timers to support progress

### ISSUE THREAD

**Issue by fritzrichter** [dalinicus/homeassistant-acinfinity#77]
I'd like to use the Timer Bar Card (https://github.com/rianadon/timer-bar-card) to display the current light cycle. Currently the remaining time is measured in seconds and stored as state.

In order to support the timer bar, it would be beneficial to add more attributes to the timer according to this diagram (https://github.com/rianadon/timer-bar-card/blob/main/images/timerbar-config.png).

So for example:
* StartTime
* EndTime
* Duration
* Active State: On/Off

**Comment by fritzrichter** [comment]
I see, so basically all information are there "somehow", in order to make the progress-bar work out of the box my suggested entity would be similar to a timer and would look like this (we just need the start and end date as new attributes)

<img width="758" alt="Bildschirmfoto 2024-09-10 um 18 28 49" src="https://github.com/user-attachments/assets/8a1b3e66-dc4d-4308-b820-985cd7de3cc0">

With these attributes, the progress bar could look like that:
<img width="898" alt="Bildschirmfoto 2024-09-10 um 18 28 39" src="https://github.com/user-attachments/assets/1caebccb-58c3-4d55-b4c4-8709792b6416">

**Comment by dalinicus** [comment]
Would this be functionally distinct from the existing `Remaining Time` entity?

![image](https://github.com/user-attachments/assets/93892a81-00dc-483a-8926-1edcea70da3b)

(I do notice that `Remaining Time` its missing from the README doc.  I'll add it)

**Comment by dalinicus** [comment]
Playing around with the card, I think I understand the ask.  I'll see if I can get it to work with what already exists using configuration.  If not, I can investigate what would need to be done to support something like this.

**Comment by dalinicus** [comment]
In my local dev environment, I created a new entity called `next_state_change` that is calculates a timestamp based on `remaining_time` and the current time in the timezone configured for the controller.  I was able to get it working.  Something like this what you're looking for?

```
type: custom:timer-bar-card
entity: binary_sensor.development_harness_light_state
end_time:
  entity: sensor.development_harness_light_next_state_change
debug: true
```

![image](https://github.com/user-attachments/assets/99bfc984-4108-46af-bc26-3b682a990b78)

**Comment by dalinicus** [comment]
given no response, I'll assume this meets your needs based on my testing.   I have a few more features I want to knock out, but this will be included in the next release.

**Comment by dalinicus** [comment]
This is now available in [1.8.0](https://github.com/dalinicus/homeassistant-acinfinity/releases/tag/1.8.0)

**Comment by fritzrichter** [comment]
Oh wow, I somehow missed the responses here and just saw the new release! Wonderful and thank you so much for your contribution ;) 💪💪💪

**Comment by almighty059** [comment]
@fritzrichter have you got the `custom:timer-bar-card` to work correctly with the new updated entitles of `remaining_time` and `next_state_change`.? If so, how did you configure the card? 

I tried several card configurations to show the progress of whatever "timed" mode is selected (Schedule, Timer to On, Timer to Off, and Cycle) but keep running into issues. For example, the below configuration works with Timer to Off because the timer start time is based on the state changing to "on". However, this doesn't apply to Timer to On mode because the state remains "off" when starting.

```
  - type: custom:timer-bar-card
    entity: select.tent_001_port_003_state
    name: Timer
    duration:
      entity: sensor.tent_001_port_003_remaining_time
      units: seconds
    end_time:
      entity: sensor.tent_001_port_003_next_state_change
    guess_mode: false
```

Is there a way to have one timer card work with all "timed" modes or do I need to make separate timer cards for each one and figure out a way to establish a start time for each? I've also tried changing `guess_mode` to "true" as well as some of the other things suggested in the card documentation but nothing seems to work.

**Comment by almighty059** [comment]
UPDATE: I've made some progress and think I've mostly figured this out (working on this was better than watching the Chicago Bears lose. 🤦‍♂️🤷‍♂️)

In short, if you only want to see the remaining time countdown "live" in the hh:mm:ss format without displaying the bar, there shouldn't be an issue. However, if you also want an accurate timer bar, there are still several issues I haven’t yet resolved. I'll do my best to explain them...

- Each mode requires either a remaining time or an end time to keep the progress bar accurate, and a start time or duration time to display the length of the timer bar so that it’s proportionally correct.
- By default, the card expects these times in either the 2021-09-07T20:24:13+00:00 format (used only by the new `next_state_change` entity) or the hh:mm:ss format. Other time formats can be specified using "units" or by setting a fixed time. However, several issues still remain, which I’ll explain later.
- The easiest part to set up is the timer's progress bar. This can be done by using the `next_state_change` entity as the "end_time." A `remaining_time` entity is also listed as an option, but the timer card requires it to update every second to function properly, which it does not. If you only want the "live" countdown without a progress bar, this should be all you need.
- The main issue lies in setting and displaying the correct overall length of the timer bar. This requires a start time or duration, which can be gotten in several ways.
- One option is using "guess mode," but it’s incompatible with the AC integration for two reasons. First, if a mode is selected that starts with the state "off," there’s no basis for a time guess. Second, if a mode begins with the state "on," the system uses that as the start time but doesn’t adjust it if the "timed" settings change. The timer bar will remain as the initial start time guessed when the mode was selected.
- Using "active_state" is another approach. This sets the start time to when the assigned entity becomes active; however, it has the same issues as guess mode. Instead, I used "active_state" in a different way. The timer card allows multiple entities to be configured in the same card so that each displays a separate timer bar. However, I only want the active one displayed. To do this I assigned a different `active_mode` entity to each "active_state" and used the "filter" function to hide the idle ones.
- The final method is to assign a specific entity to the start time or duration. This is easy to do for the Timer to On and Timer to Off modes. Simply assign the `timer_minutes_to_off` or `timer_minutes_to_on` entity to the "duration" of the appropriate configuration. Then since it doesn't follow the default time formats, use `units: minutes` to specify the format.
- However, this doesn’t work the same way for the Cycle and Schedule modes. Unlike the Timer modes, which have a single start and stop, these modes involve repetitive starts and stops, often with varying "on" and "off" times. This creates an issue because, as far as I know, there’s no way to differentiate between these instances and display the correct duration.
- I may have made this explanation more confusing than it needs to be, so below is a working example for reference. Just swap out my entities with yours to see what I mean. The first two work fine. The second two are split into four so you could see how the different set times affect each. For Cycle mode there's no way to defernite between the duration of the time on or off. And for Schedule mode the `scheduled_off_time` and `scheduled_on_time` are in hh:mm:ss format so the timer card interprets it as a total amount of time opposed to a specific time like it's meant to be.

```
type: custom:timer-bar-card
entities:
  - entity: select.tent_001_port_003_active_mode
    name: Timer to Off
    active_state: Timer to Off
    duration:
      entity: number.tent_001_port_003_timer_minutes_to_off
      units: minutes
    end_time:
      entity: sensor.tent_001_port_003_next_state_change
  - entity: select.tent_001_port_003_active_mode
    name: Timer to On
    active_state: Timer to On
    duration:
      entity: number.tent_001_port_003_timer_minutes_to_on
      units: minutes
    end_time:
      entity: sensor.tent_001_port_003_next_state_change
  - entity: select.tent_001_port_003_active_mode
    name: Cycle Off
    active_state: Cycle
    duration:
      entity: number.tent_001_port_003_cycle_minutes_off
      units: minutes
    end_time:
      entity: sensor.tent_001_port_003_next_state_change
  - entity: select.tent_001_port_003_active_mode
    name: Cycle On
    active_state: Cycle
    duration:
      entity: number.tent_001_port_003_cycle_minutes_on
      units: minutes
    end_time:
      entity: sensor.tent_001_port_003_next_state_change
  - entity: select.tent_001_port_003_active_mode
    name: Schedule Off
    active_state: Schedule
    duration:
      entity: time.tent_001_port_003_scheduled_off_time
    end_time:
      entity: sensor.tent_001_port_003_next_state_change
  - entity: select.tent_001_port_003_active_mode
    name: Schedule Off
    active_state: Schedule
    duration:
      entity: time.tent_001_port_003_scheduled_on_time
    end_time:
      entity: sensor.tent_001_port_003_next_state_change
filter: true
sync_issues: ignore
debug: true
```
